
version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - .env
    ports:
      - "8889:50070"
    networks:
      - bigdata
    
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - .env
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    networks:
      - bigdata
      
  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode2:/hadoop/dfs/data
    env_file:
      - .env
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    networks:
      - bigdata
      
  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode3:/hadoop/dfs/data
    env_file:
      - .env
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    networks:
      - bigdata
      
  datanode4:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    volumes:
      - datanode4:/hadoop/dfs/data
    env_file:
      - .env
    environment:
      SERVICE_PRECONDITION: "namenode:8020"
    networks:
      - bigdata

volumes:
  namenode:
  datanode:
  datanode2:
  datanode3:
  datanode4:

networks:
  bigdata: