version: '3'

services:
  spark-master:
    image: docker.io/bitnami/spark:3.1.2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
    networks:
      - spark
  
  spark-worker:
    image: docker.io/bitnami/spark:3.1.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
     - spark
    deploy:
      mode: replicated
      replicas: 4
  
  jupyter:
    build: 
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes: 
      - ./work:/home/jupyter/work
    environment: 
      - "SPARKMONITOR_UI_HOST=spark-master"
      - "SPARKMONITOR_UI_PORT=8080"
    networks:
      - spark

networks:
  spark:
